<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.19" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Utility.Kafka.2025" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Unipr.Magazzino.Business\Unipr.Magazzino.Business.csproj" />
    <ProjectReference Include="..\Unipr.Magazzino.Repository\Unipr.Magazzino.Repository.csproj" />
    <ProjectReference Include="..\Unipr.Magazzino.Shared\Unipr.Magazzino.Shared.csproj" />
  </ItemGroup>

</Project>
