services:
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: p4ssw0rD
    ports:
      - 2433:1433
    volumes:
      - "mssql-server:/var/opt/mssql"

  adminer:
    image: adminer:4.8.1
    ports:
      - 2431:8080
    environment:
      TZ: Europe/Rome
      ADMINER_DEFAULT_SERVER: mssql-server
      
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'host.docker.internal:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      
  unipr-ordini:
    image: ghcr.io/${GITHUB_USERNAME}/unipr-ordini:latest
    pull_policy: always
    ports:
      - "5067:8080"
    depends_on:
      - mssql-server
      - kafka
    environment:
      TZ: Europe/Rome
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - "./config/unipr-ordini-appsettings.json:/app/appsettings.json:ro"
      
  unipr-magazzino:
    image: ghcr.io/${GITHUB_USERNAME}/unipr-magazzino:latest
    pull_policy: always
    ports:
      - "5068:8080"
    depends_on:
      - mssql-server
      - kafka
    environment:
      TZ: Europe/Rome
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - "./config/unipr-magazzino-appsettings.json:/app/appsettings.json:ro"
      
  unipr-pagamenti:
    image: ghcr.io/${GITHUB_USERNAME}/unipr-pagamenti:latest
    pull_policy: always
    ports:
      - "5069:8080"
    depends_on:
      - mssql-server
      - kafka
    environment:
      TZ: Europe/Rome
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - "./config/unipr-pagamenti-appsettings.json:/app/appsettings.json:ro"

volumes:
  mssql-server: