name: Publish Docker Images

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Ordini
        uses: docker/build-push-action@v5
        with:
          context: microservizi/Unipr.Ordini
          file: microservizi/Unipr.Ordini/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/unipr-ordini:latest
          build-args: |
            TOOOOMM_NUGET_USERNAME=${{ github.actor }}
            TOOOOMM_NUGET_PASSWORD=${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Magazzino
        uses: docker/build-push-action@v5
        with:
          context: microservizi/Unipr.Magazzino
          file: microservizi/Unipr.Magazzino/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/unipr-magazzino:latest
          build-args: |
            TOOOOMM_NUGET_USERNAME=${{ github.actor }}
            TOOOOMM_NUGET_PASSWORD=${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Pagamenti
        uses: docker/build-push-action@v5
        with:
          context: microservizi/Unipr.Pagamenti
          file: microservizi/Unipr.Pagamenti/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/unipr-pagamenti:latest
          build-args: |
            TOOOOMM_NUGET_USERNAME=${{ github.actor }}
            TOOOOMM_NUGET_PASSWORD=${{ secrets.GITHUB_TOKEN }}

      - name: Build and push WebApp
        uses: docker/build-push-action@v5
        with:
          context: microservizi/Unipr.Ordini/Unipr.WebApp
          file: microservizi/Unipr.Ordini/Unipr.WebApp/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/unipr-webapp:latest
          build-args: |
            TOOOOMM_NUGET_USERNAME=${{ github.actor }}
            TOOOOMM_NUGET_PASSWORD=${{ secrets.GITHUB_TOKEN }}