name: Publish Magazzino ClientHttp to GitHub Packages

on:
  push:
    branches: [ "main", "master" ]
  
    paths:
      - 'microservizi/Unipr.Magazzino/Unipr.Magazzino.ClientHttp/**'
  workflow_dispatch: #permette di avviare l'azione anche a mano dal sito di GitHub

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:
    - name: Checkout del codice
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' 

    - name: Costruisci Shared
      run: dotnet build microservizi/Unipr.Magazzino/Unipr.Magazzino.Shared/Unipr.Magazzino.Shared.csproj -c Release

    - name: Crea Pacchetto Shared
      run: dotnet pack microservizi/Unipr.Magazzino/Unipr.Magazzino.Shared/Unipr.Magazzino.Shared.csproj -c Release --no-build -o out

    - name: Costruisci ClientHttp
      run: dotnet build microservizi/Unipr.Magazzino/Unipr.Magazzino.ClientHttp/Unipr.Magazzino.ClientHttp.csproj -c Release

    - name: Crea Pacchetto ClientHttp
      run: dotnet pack microservizi/Unipr.Magazzino/Unipr.Magazzino.ClientHttp/Unipr.Magazzino.ClientHttp.csproj -c Release --no-build -o out

    - name: Pubblica su GitHub Packages
      run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"